---
########################################### Working Scripts
- name: Create dev directory
  ansible.windows.win_file:
    path: C:\\dev
    state: directory

- name: Download MariaDb installer
  ansible.windows.win_get_url:
    url: https://configprovisionaccount.blob.core.windows.net/nuix-installers/mariadb-10.6.11-winx64.msi
    dest: C:\dev

# - name: Install the MariaDb
#   ansible.windows.win_command: msiexec /i C:\\dev\\mariadb-10.6.11-winx64.msi [INSTALLDIR=C:\Program Files\Nuix\Web Platform\Nuix-MariaDb] /qn
#   args:
#     chdir: C:\dev

- name: Install the MariaDB
  win_package:
    path: C:\\dev\\mariadb-10.6.11-winx64.msi

- name: Set Root Password For MariaDB
  ansible.windows.win_powershell:
    script: |
      mysqladmin -uroot password "P@ssword"

### Set Nuix Config files Parameters



###

### Set Java Heap Size In Files



###

########################################### Working Scripts
# - name: Create MariaDb Installation Directory
#   ansible.windows.win_file:
#     path: C:\Program Files\Nuix\Web Platform\Nuix-MariaDb
#     state: directory

# - name: Install MariaDB With Choco
#   win_chocolatey:
#     name: mysql
#     choco_args:
#     - '/installLocation=C:\Program Files\Nuix\Web Platform\Nuix-MariaDb'

# - name: Install the Nuix-Investigate
#   ansible.windows.win_package:
#     path: C:\\dev\\nuix-investigate-windows-9.6.15.exe

# - name: Powershell | Install Required Powershell Modules
#   community.windows.win_psmodule:
#     name: SimplySql
#     state: latest
#     accept_license: true

# - name: Set Root Password For MariaDB
#   ansible.windows.win_powershell:
#     script: |
#       mysql -uroot -pP@ssword



# - name: install pckages
#   shell: "mv /usr/local/example.txt /tmp"
#     mv C:\\Program Files\MariaDB 10.11 C:\\Program Files\Nuix\Web Platform\Nuix-MariaDb
# remove_dependencies: true
# choco_args: --install-directory = C:\\Program Files\Nuix\Web Platform\Nuix-MariaDb


# - name: Create directory structure
#   ansible.windows.win_file:
#     path: C:\\Program Files\Nuix\Web Platform\Nuix-MariaDb
#     state: directory
